---
title: "BEE 4750 Homework 3: Dissolved Oxygen and Monte Carlo"
format:
    html:        
        warning: true
        error: true
    ipynb:
        warning: true
        error: true
        code-annotation: below
    pdf:
        include-in-header: 
           text: |
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
engine: julia
format-links: [pdf, ipynb]
---

::: {.content-visible when-format="ipynb"}
**Name**:

**ID**:
:::

::: {.callout-important icon=false}
### Due Date

Thursday, 10/03/23, 9:00pm
:::

::: {.content-visible when-format="html"}

:::{.callout-caution}

If you are enrolled in the course, make sure that you use the GitHub Classroom link provided in Ed Discussion, or you may not be able to get help if you run into problems.

Otherwise, you can [find the Github repository here]({{< var github_org.repo >}}/hw03).

:::

:::

## Overview

### Instructions


* Problem 1 asks you to implement a model for dissolved oxygen in a river with multiple waste releases and use this to develop a strategy to ensure regulatory compliance.
* Problem 2 asks you to use Monte Carlo simulation to assess how well your strategy from Problem 1 performs under uncertainty.
* Problem 3 (5750 only) asks you to identify where a third discharge should be placed to maintain regulatory compliance.


### Load Environment

The following code loads the environment and makes sure all needed packages are installed. This should be at the start of most Julia scripts.

```{julia}
#| output: false
import Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()
```

```{julia}
using Random
using Plots
using LaTeXStrings
using Distributions
```

## Problems (Total: 50/60 Points)


::: {.cell .markdown}

### Problem 1 (30 points)

A river which flows at 6 km/d is receiving waste discharges from two sources which are 15 km apart. The oxygen reaeration rate is 0.55 day^-1^, and the decay rates of CBOD and NBOD are are 0.35 and 0.25 day^-1^, respectively. The river's saturated dissolved oxygen concentration is 10m g/L.

If the characteristics of the river inflow and waste discharges are given in @tbl-river, write a Julia model to compute the dissolved oxygen concentration from the first wastewater discharge to an arbitrary distance `d` km downstream. Use your model to compute the maximum dissolved oxygen concentration up to 50km downstream and how far downriver this maximum occurs.

| Parameter | River Inflow | Waste Stream 1 | Waste Stream 2 |
|:---------:|-------------:|---------------:|---------------:|
| Inflow | 100,000 m^3^/d | 10,000 m^3^/d | 15,000 m^3^/d |
| DO Concentration | 7.5 mg/L | 5 mg/L | 5 mg/L |
| CBOD | 5 mg/L | 50 mg/L | 45 mg/L |
| NBOD | 5 mg/L | 35 mg/L | 35 mg/L |
: River inflow and waste stream characteristics for Problem 1. {#tbl-river}

**In this problem**:

* Plot the dissolved oxygen concentration from the first waste stream to 50m downriver. What is the minimum value in mg/L?
* What is the minimum level of treatment (% removal of organic waste) for waste stream 1 that will ensure that the dissolved oxygen concentration never drops below 4 mg/L, assuming that waste stream 2 remains untreated? How about if only waste stream 2 is treated?
* Suppose you are responsible for designing a waste treatment plan for discharges into the river, with a regulatory mandate to keep the dissolved oxygen concentration above 4 mg/L. Discuss whether you'd opt to treat waste stream 2 alone or both waste streams equally. What other information might you need to make a conclusion, if any?

:::

::: {.cell .markdown}
### Problem 2 (20 points)

A coastal community has a 3.0m tall levee (relative to present-day mean sea level). From analyzing tide gauge records, you determine that the annual maximum water levels (in m) follow a [Generalized Extreme Value distribution](https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.GeneralizedExtremeValue) with parameters $\text{GEV}(1.5, 0.2, 0.1)$. The target levee reliability standard is a 1% probability of overtopping (extreme water levels exceeding the levee height).

**In this problem**:

* Use Monte Carlo simulation to estimate the present-day reliability of the levee along with a 95% confidence interval for the reliability estimate. Does it comply with the reliability standard?  How many samples did you need to determine that? 
* Over the lifetime of the levee, mean local sea levels are anticipated to rise by $0.3\mathrm{m}$ with a standard deviation of $0.2\mathrm{m}$. How does this impact the future reliability of the levee? Discuss how the sea-level uncertainty impacts the uncertainty of your Monte Carlo estimate.

:::

::: {.cell .markdown}
### Problem 3 (10 points)

**This problem is only required for students in BEE 5750**.

A factory is planning a third wastewater discharge into the river downstream of the second plant. This discharge would consist of 5 m^3^/day of wastewater with a dissolved oxygen content of 4.5 mg/L and CBOD and NBOD levels of 50 and 45 mg/L, respectively.

**In this problem**:

* Assume that the treatment plan you identified in Problem 1 is still in place for the existing discharges. If the third discharge will not be treated, under the original inflow conditions (7.5 mg/L DO), how far downstream from the second discharge does this third discharge need to be placed to keep the river concentration from dropping below 4 mg/L?
:::


::: {.cell .markdown}
## References

List any external references consulted, including classmates.
:::
